import { createHash } from 'node:crypto';
import { readdir, readFile, writeFile } from 'node:fs/promises';
import { resolve } from 'node:path';
import { defineConfig, type Plugin } from 'vite';

async function filesBelow(directory: string, prefix = ''): Promise<string[]> {
  const entries = await readdir(directory, { withFileTypes: true });
  const files = await Promise.all(entries.map(async (entry) => {
    const relative = `${prefix}${entry.name}`;
    return entry.isDirectory() ? filesBelow(resolve(directory, entry.name), `${relative}/`) : [relative];
  }));
  return files.flat();
}

function pwaWorker(): Plugin {
  let outputDirectory = '';

  return {
    name: 'proofbook-generated-service-worker',
    apply: 'build',
    configResolved(config) {
      outputDirectory = resolve(config.root, config.build.outDir);
    },
    async closeBundle() {
      const allFiles = (await filesBelow(outputDirectory))
        // Azure consumes this deployment-only file rather than serving it. Never
        // let an unavailable deployment config prevent worker installation.
        .filter((file) => file !== 'sw.js' && file !== 'staticwebapp.config.json' && !file.endsWith('.map'))
        .sort();
      const digest = createHash('sha256');
      for (const file of allFiles) digest.update(await readFile(resolve(outputDirectory, file)));
      const buildId = digest.digest('hex').slice(0, 12);
      const precache = allFiles.map((file) => `/${file}`);

      // Keep the installed app pointed at the current shell as well as generating
      // a cache name that can never describe an earlier Vite output.
      const manifestPath = resolve(outputDirectory, 'manifest.webmanifest');
      const manifest = JSON.parse(await readFile(manifestPath, 'utf8')) as Record<string, unknown>;
      manifest.start_url = `/app?v=${buildId}`;
      await writeFile(manifestPath, `${JSON.stringify(manifest, null, 2)}\n`);

      const worker = `/* Generated by vite.config.ts. Do not edit this file. */
const CACHE = 'proofbook-${buildId}';
const PRECACHE = ${JSON.stringify(precache)};

self.addEventListener('install', (event) => {
  event.waitUntil(caches.open(CACHE).then((cache) => cache.addAll(PRECACHE)).then(() => self.skipWaiting()));
});

self.addEventListener('activate', (event) => {
  event.waitUntil(caches.keys().then((keys) => Promise.all(
    keys.filter((key) => key.startsWith('proofbook-') && key !== CACHE).map((key) => caches.delete(key)),
  )).then(() => self.clients.claim()));
});

self.addEventListener('message', (event) => {
  if (event.data === 'SKIP_WAITING') self.skipWaiting();
});

self.addEventListener('fetch', (event) => {
  if (event.request.method !== 'GET') return;
  const url = new URL(event.request.url);
  if (url.origin !== self.location.origin) return;

  if (event.request.mode === 'navigate') {
    event.respondWith((async () => {
      try {
        const response = await fetch(event.request);
        if (response.ok) {
          const cache = await caches.open(CACHE);
          await cache.put('/index.html', response.clone());
        }
        return response;
      } catch {
        return (await caches.match('/index.html')) || (await caches.match('/offline.html')) || Response.error();
      }
    })());
    return;
  }

  event.respondWith(caches.match(event.request).then(async (cached) => {
    if (cached) return cached;
    const response = await fetch(event.request);
    if (response.ok) (await caches.open(CACHE)).put(event.request, response.clone());
    return response;
  }));
});
`;
      await writeFile(resolve(outputDirectory, 'sw.js'), worker);
    },
  };
}

export default defineConfig({
  plugins: [pwaWorker()],
  build: {
    target: 'es2022',
    sourcemap: true,
  },
});
